Feature branch fixed after Kostya commit
pavelb2p/MyCrudProject pull request #2
Opened 2022-04-05 15:09 UTC by pavelb2p

Uncommented Dockerfile, Binary file added to gitignore,format pom.xml properly(remove comments etc), removed unused import lines in files, uncommented files: MyCrudProjectApplicationTests.java and application.properties

2022-04-08 10:29 UTC, kastyan-kg requested changes

2022-04-08 10:29 UTC, kastyan-kg commented on src/main/java/com/example/mycrudproject/entity/Display.java
> +package com.example.mycrudproject.entity;
it's not an entity, it can be dto, payload etc 
Also Display -  No usages found in All Places ;)

2022-04-08 10:29 UTC, kastyan-kg commented on src/main/java/com/example/mycrudproject/entity/Feed.java
> +import javax.persistence.*;
usually * import is not allowed, you can set your IDE to avoid this

2022-04-08 10:29 UTC, kastyan-kg commented on src/main/java/com/example/mycrudproject/service/impl/FeedServiceImpl.java
> +    @Autowired
@RequreidArgConstructor + final fields for injection

2022-04-08 10:29 UTC, kastyan-kg commented on src/main/java/com/example/mycrudproject/service/impl/FeedServiceImpl.java
> +    private FeedRepository feedRepository;
@RequreidArgConstructor + final fields for injection

2022-04-08 10:29 UTC, kastyan-kg commented on src/main/java/com/example/mycrudproject/service/impl/UserServiceImpl.java
> +    @Autowired
@RequreidArgConstructor + final fields for injection

2022-04-08 10:29 UTC, kastyan-kg commented on src/main/java/com/example/mycrudproject/service/impl/UserServiceImpl.java
> +        Optional<User> findById = userRepository.findById(id);
use declaritive style with Optional, also what will be if user is not found?

2022-04-08 10:29 UTC, kastyan-kg commented on src/main/java/com/example/mycrudproject/service/impl/UserServiceImpl.java
> +        userRepository.deleteById(id);
what will be if there is no such user?

2022-04-13 15:18 UTC, pavelb2p commented on src/main/java/com/example/mycrudproject/controller/FeedController.java
> +@RequestMapping("/")
I didnt wrote something after "/", because I think, if we are going to add new Entities into our project, we should change main URL RequestMapping. It will be easy create new url by our new Entities.

2022-04-13 15:29 UTC, pavelb2p commented on src/main/java/com/example/mycrudproject/controller/FeedController.java
> +    @PostMapping("/feeds")
Sorry, but I think "Use “verb”" - its Anti-Patterns. Because users dont need to know what do this url.  Bad practice use: /save, /create, /update etc.

2022-04-13 15:31 UTC, pavelb2p commented on src/main/java/com/example/mycrudproject/controller/UserController.java
> +    @PostMapping("/users")
Its bad practice in RESTApi to use words that mean action

2022-04-13 15:47 UTC, pavelb2p commented on src/main/java/com/example/mycrudproject/controller/UserController.java
> +    @GetMapping("/users")
im going to discuss it, ok?

2022-04-13 15:54 UTC, pavelb2p commented on src/main/java/com/example/mycrudproject/entity/Display.java
> +package com.example.mycrudproject.entity;
Ow,  it was an old class i forgot to delete it

2022-04-21 08:25 UTC, pavelb2p commented on src/main/java/com/example/mycrudproject/controller/FeedController.java
> +    @Autowired
done

2022-04-21 08:26 UTC, pavelb2p commented on src/main/java/com/example/mycrudproject/controller/FeedController.java
> +@RequestMapping("/")
done

2022-04-26 15:17 UTC, closed without merging